name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 只匹配以 v 开头的标签，如 v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name (if present)
        id: extract_tag
        shell: bash
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Debug GIT_TAG
        run: echo "Tag is $GIT_TAG"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            jaaksi/sublinkx:latest
            jaaksi/sublinkx:${{ env.GIT_TAG }}
